export const nutritionalFacts = {
  title: "Tania Lee Facts",
  description: "elizatanialee@gmail.com | +65 8305 3749 | linkedin.com/in/tanilee",
  dateofProduction: "21/11/2025",
  education: [{school: "SMU", degree: "BSc in Computer Science", dates: "2023-2027"}],
  workingExperience: [
    { label: "Data Scientist Intern", company: "Blitz Electric Mobility", date: "Jun 2025 - Present", content: "Hybrid Internship"},
    { label: "LKYGBPC Student Leader", company: "SMU Institute of Innovation & Entrepreneurship", date: "Oct 2024 - May 2025", content: "Part-time Internship"},
    { label: "Freelance Designer", company: null, date: "May 2023 - August 2023"},
  ],
  activities: [
    { label: "Coders Assembly Marketing Director", company: "SMU Coders Assembly", date: "May 2024 - May 2025"},
    { label: "ICON Camp 2024 Marketing Director", company: "SMU International Connections", date: "Feb 2024 - Oct 2024"},
    { label: "AIESEC in Singapore", company: "AIESEC", date: "Jan 2024 - Dec 2024"},
    { label: "SWC Marketing Associate", company: "SMU Women's Connection", date: "Jan 2024 - Dec 2024"},
    { label: "International Scholars Organizing Committee", company: "Student Success Centre", date: "Jan 2024 - Sep 2024"},
  ],
  skills: [
    { label: "Java", value: "69%" },
    { label: "Python", value: "67%" },
    { label: "Javascript", value: "68%" },
    { label: "SQL", value: "78%" },
    { label: "Figma", value: "79%" },
    { label: "Go", value: "0.01%" },
    { label: "Adobe PS", value: "92%" },
    { label: "Canva", value: "97%" },
    { label: "English", value: "Fluent" },
    { label: "Indonesia", value: "Fluent" },
    { label: "Korean", value: "Basic" },
  ],
  disclaimer: "Percentage values are based on a personal opinion.",
};
